name: Test
on:
  push:
    paths-ignore:
      - '**/*.md'
  schedule:
    # UTC
    - cron: '15 12 * * *'
env:
  TERM: xterm-256color
jobs:
  make:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make nightly build check latest isle-buildkit
        if: github.event_name == 'schedule'
        run: |-
          echo "TAG=main" >> $GITHUB_OUTPUT

      - name: init secrets
        run: |-
          cp sample.env .env
          ./build/scripts/check-secrets.sh yes
        shell: bash

      - name: make starter
        run: make starter
        shell: bash

      - name: check online
        run: ./scripts/ci/ping.sh

      - name: "Make sure we can export the site config through the UI"
        run: ./scripts/ci/drush-cex-ui.sh

      - name: make build
        run: make build
        shell: bash

      - name: make production
        run: make production
        shell: bash

      - name: check online
        run: ./scripts/ci/ping.sh

      - name: Notify Slack on nightly test failure
        if: failure() && github.event_name == 'schedule'
        run: |-
          curl -s -o /dev/null -XPOST $SLACK_WEBHOOK_URL -d '{
            "text": "🚨 Scheduled job failed! Click to view the run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|GitHub Actions Run>",
          }'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
